# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=35)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
